openapi: 3.0.0
info:
  title: Evaluation Webhook (inferred)
  version: '1.0'
paths:
  /webhook/commoon/upload-audio:
    post:
      summary: Upload audio segment for evaluation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                startSlide:
                  type: integer
                endSlide:
                  type: integer
                audience:
                  type: string
      responses:
        '200':
          description: Evaluation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  input:
                    type: string
                  output:
                    type: string
